// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform, debugPrint;
import 'package:carenest/config/environment.dart';

class DefaultFirebaseOptions {
  static String _getEnv(String key, {String fallback = ''}) {
    switch (key) {
      case 'FIREBASE_WEB_API_KEY':
        return const String.fromEnvironment('FIREBASE_WEB_API_KEY');
      case 'FIREBASE_ANDROID_API_KEY':
        return const String.fromEnvironment('FIREBASE_ANDROID_API_KEY');
      case 'FIREBASE_ANDROID_DEV_API_KEY':
        return const String.fromEnvironment('FIREBASE_ANDROID_DEV_API_KEY');
      case 'FIREBASE_IOS_API_KEY':
        return const String.fromEnvironment('FIREBASE_IOS_API_KEY');
    }
    return fallback;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: _getEnv('FIREBASE_WEB_API_KEY'),
    appId: '1:406509736623:web:default',
    messagingSenderId: '406509736623',
    projectId: 'invoice-660f3',
    authDomain: 'invoice-660f3.firebaseapp.com',
    storageBucket: 'invoice-660f3.appspot.com',
  );

  static FirebaseOptions get androidProduction => FirebaseOptions(
    apiKey: _getEnv('FIREBASE_ANDROID_API_KEY'),
    appId: '1:406509736623:android:73088e652df1e5346a3a5a',
    messagingSenderId: '406509736623',
    projectId: 'invoice-660f3',
    storageBucket: 'invoice-660f3.appspot.com',
  );

  static FirebaseOptions get androidDevelopment => FirebaseOptions(
    apiKey: _getEnv('FIREBASE_ANDROID_DEV_API_KEY'),
    appId: '1:406509736623:android:a015207404bd0c726a3a5a',
    messagingSenderId: '406509736623',
    projectId: 'invoice-660f3',
    storageBucket: 'invoice-660f3.appspot.com',
  );

  static FirebaseOptions get android {
    final isDevelopment = AppConfig.appFlavor == Flavor.development;
    debugPrint(
      '🔥 Firebase Options: Using ${isDevelopment ? "DEVELOPMENT" : "PRODUCTION"} Android config',
    );
    debugPrint(
      '🔥 App ID: ${isDevelopment ? androidDevelopment.appId : androidProduction.appId}',
    );

    if (isDevelopment) {
      return androidDevelopment;
    }
    return androidProduction;
  }

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _getEnv('FIREBASE_IOS_API_KEY'),
    appId: '1:406509736623:ios:80ba46b45d8930db6a3a5a',
    messagingSenderId: '406509736623',
    projectId: 'invoice-660f3',
    storageBucket: 'invoice-660f3.appspot.com',
    iosBundleId: 'com.bishal.invoice',
  );
}
