# This file contains the fastlane configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Increment version code"
  lane :increment_version_code do
    # Read current version from local.properties
    properties_file = "../local.properties"
    properties = {}
    
    if File.exist?(properties_file)
      File.readlines(properties_file).each do |line|
        key, value = line.strip.split('=', 2)
        properties[key] = value if key && value
      end
    end
    
    current_version_code = (properties['flutter.versionCode'] || '1').to_i
    new_version_code = current_version_code + 1
    
    # Update version code in local.properties
    updated_content = []
    version_code_updated = false
    
    if File.exist?(properties_file)
      File.readlines(properties_file).each do |line|
        if line.start_with?('flutter.versionCode=')
          updated_content << "flutter.versionCode=#{new_version_code}\n"
          version_code_updated = true
        else
          updated_content << line
        end
      end
    end
    
    # Add version code if it wasn't found
    unless version_code_updated
      updated_content << "flutter.versionCode=#{new_version_code}\n"
    end
    
    File.write(properties_file, updated_content.join)
    
    UI.message "Version code incremented from #{current_version_code} to #{new_version_code}"
  end

  desc "Capture screenshots for the store"
  lane :capture_screenshots do
    # Build APKs for testing (using development flavor)
    sh "cd .. && ./gradlew assembleDevelopmentDebug assembleDevelopmentDebugAndroidTest"
    
    screengrab(
      app_apk_path: "../build/app/outputs/apk/development/debug/app-development-debug.apk",
      tests_apk_path: "../build/app/outputs/apk/androidTest/development/debug/app-development-debug-androidTest.apk",
      app_package_name: "com.bishal.invoice.dev",
      locales: ["en-US"],
      clear_previous_screenshots: true
    )
  end

  desc "Deploy development build to internal testing"
  lane :deploy_development do
    # Build the production AAB (development track uses production flavor)
    sh "cd .. && flutter build appbundle --flavor production -t lib/main_production.dart --release"
    
    # Read version info from local.properties
    properties_file = "../local.properties"
    properties = {}
    
    if File.exist?(properties_file)
      File.readlines(properties_file).each do |line|
        key, value = line.strip.split('=', 2)
        properties[key] = value if key && value
      end
    end
    
    version_name = properties['flutter.versionName'] || '1.0'
    version_code = properties['flutter.versionCode'] || '1'
    
    # Generate release notes from file if exists
    release_notes_file = "../release_notes_#{version_name}.txt"
    if File.exist?(release_notes_file)
      UI.message "Found release notes file: #{release_notes_file}"
      release_notes = File.read(release_notes_file)
    else
      UI.message "Release notes file not found at #{release_notes_file}, using default."
      release_notes = "Development build #{version_name} (#{version_code})\n\nAutomated build for internal testing."
    end
    
    # Create metadata directory if it doesn't exist
    metadata_dir = "metadata/android/en-US"
    FileUtils.mkdir_p(metadata_dir)
    FileUtils.mkdir_p("#{metadata_dir}/changelogs")
    
    # Write changelog
    File.write("#{metadata_dir}/changelogs/#{version_code}.txt", release_notes)
    
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/productionRelease/app-production-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy production build to production track"
  lane :deploy_production do
    # Build the production AAB
    sh "cd .. && flutter build appbundle --flavor production -t lib/main_production.dart --release"
    
    # Read version info from local.properties
    properties_file = "../local.properties"
    properties = {}
    
    if File.exist?(properties_file)
      File.readlines(properties_file).each do |line|
        key, value = line.strip.split('=', 2)
        properties[key] = value if key && value
      end
    end
    
    version_name = properties['flutter.versionName'] || '1.0'
    version_code = properties['flutter.versionCode'] || '1'
    
    # Generate release notes from file if exists
    release_notes_file = "../release_notes_#{version_name}.txt"
    if File.exist?(release_notes_file)
      UI.message "Found release notes file: #{release_notes_file}"
      release_notes = File.read(release_notes_file)
    else
      UI.message "Release notes file not found at #{release_notes_file}, using default."
      release_notes = "Production release #{version_name} (#{version_code})\n\nStable release for production."
    end
    
    # Create metadata directory if it doesn't exist
    metadata_dir = "metadata/android/en-US"
    changelog_dir = "#{metadata_dir}/changelogs"
    FileUtils.mkdir_p(changelog_dir)
    
    # Write changelog
    File.write("#{changelog_dir}/#{version_code}.txt", release_notes)
    
    upload_to_play_store(
      track: 'production',
      package_name: 'com.bishal.invoice',
      aab: '../build/app/outputs/bundle/productionRelease/app-production-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy internal build to internal testing"
  lane :deploy_internal do
    # Build the production AAB (internal uses production flavor)
    sh "cd .. && flutter build appbundle --flavor production -t lib/main_production.dart --release"
    
    # Read version info from local.properties
    properties_file = "../local.properties"
    properties = {}
    
    if File.exist?(properties_file)
      File.readlines(properties_file).each do |line|
        key, value = line.strip.split('=', 2)
        properties[key] = value if key && value
      end
    end
    
    version_name = properties['flutter.versionName'] || '1.0'
    version_code = properties['flutter.versionCode'] || '1'
    
    # Generate release notes from file if exists
    release_notes_file = "../release_notes_#{version_name}.txt"
    if File.exist?(release_notes_file)
      UI.message "Found release notes file: #{release_notes_file}"
      release_notes = File.read(release_notes_file)
    else
      UI.message "Release notes file not found at #{release_notes_file}, using default."
      release_notes = "Internal build #{version_name} (#{version_code})\n\nInternal testing build."
    end
    
    # Create metadata directory if it doesn't exist
    metadata_dir = "metadata/android/en-US"
    changelog_dir = "#{metadata_dir}/changelogs"
    FileUtils.mkdir_p(changelog_dir)
    
    # Write changelog
    File.write("#{changelog_dir}/#{version_code}.txt", release_notes)
    
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/productionRelease/app-production-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Upload existing production AAB to internal testing"
  lane :upload_internal_aab do
    aab_path = '../build/app/outputs/bundle/productionRelease/app-production-release.aab'
    UI.user_error!("AAB not found at #{aab_path}. Build it first.") unless File.exist?(aab_path)

    # Read version info from local.properties
    properties_file = "../local.properties"
    properties = {}

    if File.exist?(properties_file)
      File.readlines(properties_file).each do |line|
        key, value = line.strip.split('=', 2)
        properties[key] = value if key && value
      end
    end

    version_name = properties['flutter.versionName'] || '1.0'
    version_code = properties['flutter.versionCode'] || '1'

    release_notes_file = "../release_notes_#{version_name}.txt"
    if File.exist?(release_notes_file)
      UI.message "Found release notes file: #{release_notes_file}"
      release_notes = File.read(release_notes_file)
    else
      UI.message "Release notes file not found at #{release_notes_file}, using default."
      release_notes = "Internal build #{version_name} (#{version_code})\n\nInternal testing build."
    end

    metadata_dir = "metadata/android/en-US"
    changelog_dir = "#{metadata_dir}/changelogs"
    FileUtils.mkdir_p(changelog_dir)
    File.write("#{changelog_dir}/#{version_code}.txt", release_notes)

    upload_to_play_store(
      track: 'internal',
      aab: aab_path,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Upload existing production AAB to production track"
  lane :upload_production_aab do
    aab_path = '../build/app/outputs/bundle/productionRelease/app-production-release.aab'
    UI.user_error!("AAB not found at #{aab_path}. Build it first.") unless File.exist?(aab_path)

    properties_file = "../local.properties"
    properties = {}

    if File.exist?(properties_file)
      File.readlines(properties_file).each do |line|
        key, value = line.strip.split('=', 2)
        properties[key] = value if key && value
      end
    end

    version_name = properties['flutter.versionName'] || '1.0'
    version_code = properties['flutter.versionCode'] || '1'

    release_notes_file = "../release_notes_#{version_name}.txt"
    if File.exist?(release_notes_file)
      UI.message "Found release notes file: #{release_notes_file}"
      release_notes = File.read(release_notes_file)
    else
      UI.message "Release notes file not found at #{release_notes_file}, using default."
      release_notes = "Production release #{version_name} (#{version_code})\n\nStable release for production."
    end

    metadata_dir = "metadata/android/en-US"
    changelog_dir = "#{metadata_dir}/changelogs"
    FileUtils.mkdir_p(changelog_dir)
    File.write("#{changelog_dir}/#{version_code}.txt", release_notes)

    upload_to_play_store(
      track: 'production',
      package_name: 'com.bishal.invoice',
      aab: aab_path,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
